title = "Childlike wonder?"
date = "2022/09/08"
content = '''
<p>So, on to week two.  I feel like I'm learning an immense ammount of stuff - most notably I think there's an
important amount of knowledge that can be gained from my course in statistics and my software engineering course.
</p>
<p>
Neither course is as directly targeted at the research I'm doing like my course in artificial intelligence course -
which ultimately is the backbone of the research I'm going to be doing... but I'll say there is an immense amount that
can be learned from both of the courses.  In particular, in the SWE course, I think the way I've been doing project planning
for coursework and research has been wrong
</p>
<h3>Should I be doing my research like an agile project?</h3>
<p>
I kind of hate all these project management frameworks, they all seem kind of silly and focused on the wrong thing in
practice (or at least in my exceedingly limited ad hoc exposure to it, and popular tech bro culture).  Actually, that's
not entirely true - I just hate the nomenclature of it.  "Epic," "story," "scrum" - we're writing code not fighting dragons.
</p><p>
That said, I truly
think that the ability to iterate continuously on your research, and breaking your research down into "Epics" (shudder) and specific
job tasks down as "stories" might have a huge amount of efficiency gains.  Additionally, I think it could make me a more
productive researcher?  This is just a project - arguably it's a software project, why should it be any different from a
commercial one?
</p>
<p>That brings me to the automation and automated testing, etc.  I really need to be asking myself "how can I be
automating my research, and every time I submit work, how can I automate checking the work?  If it's efficient for
software developers and businesses, why can't it make me more efficient at my work?</p>
<p>Finally, this week I've kind of noticed something distressing in the student body, people seem beat down, tired,
and generally wore out.  I kind of consistently feel like I'm one of the only folks that has "childlike wonder" at
all this amazing stuff we're getting to learn about right now - mostly everyone just seems really tired.  Granted,
illness aside, I'm in an extremely fortunate position with our life and family situation - my kids are healthy, happy,
and life is good... but man, the classes all feel like a morgue some times.</p>

<p>The instructors seem dynamic and excited... but the students just seem tired - it's the second week!  It's way too
early for that sort of fatigue.  Is this the aftermath of covid?  Is everyone just... frankly burned out?  The prospects
for their future controlled by faceless bureaucrats "somewhere out there" in the ether?  Or maybe it's just been really
hard to be going to school for the last two years?</p>

<p>I don't know - but I'll say this.  The campus is a ghost town - when I went to classes here before it was packed,
and while I think it's really good that we're being responsible with covid, etc. I also think there's got to be some
sort of added financial pressure on the management folks to justify the costs associated with empty buildings etc.  I reckon
that that mind set seeps in to every sort of interaction.  The students seem lonely, isolated, and well, joyless?</p>

<p>That's fine by me - I get it, things are really hard, but I feel kind of bad to be so extraordinarily excited about
this stuff right now.  We truly live in the future.  We're studying amazing stuff.  Things that were science fiction are
 reality now! Maybe it's just me and maybe it's a factor of me getting back to doing something I am interested in doing,
 but it is pretty crazy how different it is.</p>

<p>Maybe there's a social science course I can take on Marxism or something that can put this into better perspective,
but the folks in the classes seem pretty alienated - and it's weird to see a stock ticker running to announce profits
to an empty business school.
</p>
'''